In [1]:
import numpy as np
import util

In [32]:
train_path='train.csv'
valid_path = 'valid.csv'
x_train, y_train = util.load_dataset(train_path, add_intercept=True)
x_eval, y_eval = util.load_dataset(valid_path, add_intercept=True)

In [4]:
x_train

array([[1.        , 1.        , 0.        , 2.97614241, 0.65148205],
       [1.        , 0.        , 1.        , 1.4113903 , 0.74373156],
       [1.        , 0.        , 1.        , 1.03989184, 1.2905879 ],
       ...,
       [1.        , 0.        , 1.        , 1.49124324, 0.84115559],
       [1.        , 0.        , 1.        , 2.8631773 , 1.13793409],
       [1.        , 0.        , 1.        , 1.82561719, 0.05930945]])

In [33]:
class PoissonRegression:
    """Poisson Regression.

    Example usage:
        > clf = PoissonRegression(step_size=lr)
        > clf.fit(x_train, y_train)
        > clf.predict(x_eval)
    """

    def __init__(self, step_size=1e-5, max_iter=10000000, eps=1e-5,
                 theta_0=None, verbose=True):
        """
        Args:
            step_size: Step size for iterative solvers only.
            max_iter: Maximum number of iterations for the solver.
            eps: Threshold for determining convergence.
            theta_0: Initial guess for theta. If None, use the zero vector.
            verbose: Print loss values during training.
        """
        self.theta = theta_0
        self.step_size = step_size
        self.max_iter = max_iter
        self.eps = eps
        self.verbose = verbose

    def fit(self, x, y):
        """Run gradient ascent to maximize likelihood for Poisson regression.

        Args:
            x: Training example inputs. Shape (n_examples, dim).
            y: Training example labels. Shape (n_examples,).
        """
        # *** START CODE HERE ***
        n, d = x.shape
        if self.theta is None:
            self.theta = np.zeros(d)

        step = 0
        diff = 0.1
        while step <= self.max_iter and diff >= self.eps:
            theta_prev = self.theta.copy()
            eta = np.matmul(x, self.theta)
            update = np.matmul((y-np.exp(eta)),x)
            self.theta += self.step_size*update
            
            diff = np.linalg.norm(self.theta - theta_prev)
            step += 1
            
#             self.theta += self.step_size*(y-np.exp(eta))

        
        # *** END CODE HERE ***

    def predict(self, x):
        """Make a prediction given inputs x.

        Args:
            x: Inputs of shape (n_examples, dim).

        Returns:
            Floating-point prediction for each input, shape (n_examples,).
        """
        # *** START CODE HERE ***
        eta = np.matmul(x, self.theta)
        y_pred = np.exp(eta)
        return y_pred
        # *** END CODE HERE ***

In [34]:
clf = PoissonRegression()

In [35]:
clf.fit(x_train,y_train)

In [36]:
clf.theta

array([0.94784589, 0.50502207, 0.44282382, 0.28191488, 0.40006766])

In [37]:
clf.predict(x_eval)

array([ 9.6994769 ,  7.15980712, 11.75753663,  7.31602849, 17.61128888,
        6.24270577,  7.64730369,  8.11447304,  8.75235474,  6.3521577 ,
        5.43868717,  6.74570082,  8.24325121,  9.51519315,  9.06942881,
        9.59675288,  8.69959986, 12.46853992,  9.11064225,  9.51640579,
        7.47002468, 11.12809987,  8.38274106,  6.98856604,  6.06668161,
        5.82889038, 14.79465438,  6.12179143, 14.11193994,  5.40749561,
        9.76835409,  7.96141416,  7.63766028, 11.16028932, 10.40672254,
       12.57720436,  8.41271795,  6.82063097, 10.24051735,  5.73448579,
        4.6885167 , 12.54264504,  6.6219376 ,  8.74520804, 15.09063191,
       10.30687783, 10.07599363,  7.43852405,  8.16559207, 11.91389883,
        7.63448704,  9.093541  ,  9.99806125,  6.3853314 , 13.52198568,
        7.6656791 ,  6.8569351 , 10.22093235,  9.57622082,  9.91189675,
        7.27702868,  7.94532484, 13.95853286,  6.5807126 , 16.23833692,
        6.47840802,  8.43491512,  5.67997835, 13.08658609,  8.39