In [1]:
import util
import numpy as np
import matplotlib.pyplot as plt
import featuremap
%matplotlib inline

In [ ]:
# classes and inheritance examples
# https://www.programiz.com/python-programming/inheritance

In [3]:
featuremap.main(train_path='train.csv', small_path='small.csv', eval_path='test.csv')

In [120]:
train_x,train_y=util.load_dataset('train.csv',add_intercept=True)

In [27]:
train_x

array([[ 1.        , -1.71359599],
       [ 1.        ,  5.77545316],
       [ 1.        ,  2.47519421],
       [ 1.        ,  3.10985939],
       [ 1.        ,  4.5061228 ],
       [ 1.        , -4.75998887]])

In [29]:
np.power(train_x,3)

array([[   1.        ,   -5.03182251],
       [   1.        ,  192.64520256],
       [   1.        ,   15.16449116],
       [   1.        ,   30.07615133],
       [   1.        ,   91.49746619],
       [   1.        , -107.8494194 ]])

In [33]:
np.repeat(train_x,2, axis=1)

array([[ 1.        ,  1.        , -1.71359599, -1.71359599],
       [ 1.        ,  1.        ,  5.77545316,  5.77545316],
       [ 1.        ,  1.        ,  2.47519421,  2.47519421],
       [ 1.        ,  1.        ,  3.10985939,  3.10985939],
       [ 1.        ,  1.        ,  4.5061228 ,  4.5061228 ],
       [ 1.        ,  1.        , -4.75998887, -4.75998887]])

In [55]:
# https://stackoverflow.com/questions/1550130/cloning-row-or-column-vectors
np.tile(np.array([train_x[:,1],]).transpose(),(1,4))

array([[-1.71359599, -1.71359599, -1.71359599, -1.71359599],
       [ 5.77545316,  5.77545316,  5.77545316,  5.77545316],
       [ 2.47519421,  2.47519421,  2.47519421,  2.47519421],
       [ 3.10985939,  3.10985939,  3.10985939,  3.10985939],
       [ 4.5061228 ,  4.5061228 ,  4.5061228 ,  4.5061228 ],
       [-4.75998887, -4.75998887, -4.75998887, -4.75998887]])

In [57]:
duped = np.tile(np.array([train_x[:,1],]).transpose(),(1,4))

In [65]:
np.hstack((train_x[:,0], duped))

ValueError: all the input arrays must have same number of dimensions

In [66]:
duped.shape

(6, 4)

In [76]:
train_x[:,0].shape

(6,)

In [85]:
single_col = np.array([train_x[:,0],]).transpose()

In [86]:
single_col.shape

(6, 1)

In [87]:
np.append(single_col,duped,1)

array([[ 1.        , -1.71359599, -1.71359599, -1.71359599, -1.71359599],
       [ 1.        ,  5.77545316,  5.77545316,  5.77545316,  5.77545316],
       [ 1.        ,  2.47519421,  2.47519421,  2.47519421,  2.47519421],
       [ 1.        ,  3.10985939,  3.10985939,  3.10985939,  3.10985939],
       [ 1.        ,  4.5061228 ,  4.5061228 ,  4.5061228 ,  4.5061228 ],
       [ 1.        , -4.75998887, -4.75998887, -4.75998887, -4.75998887]])

In [94]:
perfect = np.hstack([single_col,duped])

In [95]:
np.power(perfect,[0,1,2,3,4])

array([[ 1.00000000e+00, -1.71359599e+00,  2.93641123e+00,
        -5.03182251e+00,  8.62251089e+00],
       [ 1.00000000e+00,  5.77545316e+00,  3.33558592e+01,
         1.92645203e+02,  1.11261334e+03],
       [ 1.00000000e+00,  2.47519421e+00,  6.12658639e+00,
         1.51644912e+01,  3.75350608e+01],
       [ 1.00000000e+00,  3.10985939e+00,  9.67122545e+00,
         3.00761513e+01,  9.35326018e+01],
       [ 1.00000000e+00,  4.50612280e+00,  2.03051427e+01,
         9.14974662e+01,  4.12298818e+02],
       [ 1.00000000e+00, -4.75998887e+00,  2.26574940e+01,
        -1.07849419e+02,  5.13362036e+02]])

In [98]:
[*range(5)]

[0, 1, 2, 3, 4]

In [91]:
np.repeat(train_x[:,np.newaxis],1,3)

AxisError: axis 3 is out of bounds for array of dimension 3

In [137]:
def create_poly( k, X):
    """
    Generates a polynomial feature map using the data x.
    The polynomial map should have powers from 0 to k
    Output should be a numpy array whose shape is (n_examples, k+1)

    Args:
        X: Training example inputs. Shape (n_examples, 2).
    """
    # *** START CODE HERE ***
    polyList = [*range(k+1)]
    col_1 = np.array([X[:,0],]).transpose()
    col_2 = np.array([X[:,1],]).transpose()

    clone_col_2 = np.tile(col_2, (1,k))
    feature_cloned = np.hstack([col_1,clone_col_2])
    feature_poly = np.power(feature_cloned,polyList)
    return feature_poly

In [127]:
k=2

In [129]:
polyList = [*range(k+1)]
polyList

[0, 1, 2]

In [144]:
my_poly = create_poly(5,train_x)

In [145]:
train_x

array([[ 1.        , -1.71359599],
       [ 1.        ,  5.77545316],
       [ 1.        ,  2.47519421],
       [ 1.        ,  3.10985939],
       [ 1.        ,  4.5061228 ],
       [ 1.        , -4.75998887],
       [ 1.        ,  5.39465405],
       [ 1.        , -5.52158709],
       [ 1.        , -6.28318531],
       [ 1.        , -2.72906028],
       [ 1.        ,  6.28318531],
       [ 1.        , -2.0943951 ],
       [ 1.        , -5.64852012],
       [ 1.        , -5.39465405],
       [ 1.        , -3.99839065],
       [ 1.        ,  0.06346652],
       [ 1.        , -3.74452458],
       [ 1.        ,  6.02931923],
       [ 1.        , -1.20586385],
       [ 1.        ,  0.31733259],
       [ 1.        , -3.87145761],
       [ 1.        , -6.15625227],
       [ 1.        ,  0.95199777],
       [ 1.        , -5.26772102],
       [ 1.        ,  0.6981317 ],
       [ 1.        , -3.36372547],
       [ 1.        ,  1.96746207],
       [ 1.        , -1.84052903],
       [ 1.        ,

# 2B update $\theta$

In [103]:
my_poly.transpose()

array([[   1.        ,    1.        ,    1.        ,    1.        ,
           1.        ,    1.        ],
       [  -1.71359599,    5.77545316,    2.47519421,    3.10985939,
           4.5061228 ,   -4.75998887],
       [   2.93641123,   33.35585922,    6.12658639,    9.67122545,
          20.30514265,   22.65749403],
       [  -5.03182251,  192.64520256,   15.16449116,   30.07615133,
          91.49746619, -107.8494194 ]])

In [105]:
my_poly.transpose().dot(my_poly)

array([[6.00000000e+00, 9.39304470e+00, 9.50527190e+01, 2.16502069e+02],
       [9.39304470e+00, 9.50527190e+01, 2.16502069e+02, 2.17796437e+03],
       [9.50527190e+01, 2.16502069e+02, 2.17796437e+03, 6.20912209e+03],
       [2.16502069e+02, 2.17796437e+03, 6.20912209e+03, 5.82753136e+04]])

In [106]:
my_poly.transpose().dot(train_y)

array([  -0.59456649,   -7.63678614,   -8.44256009, -290.48666046])

In [109]:
def fit(X, y):
    """Run solver to fit linear model. You have to update the value of
    self.theta using the normal equations.

    Args:
        X: Training example inputs. Shape (n_examples, dim).
        y: Training example labels. Shape (n_examples,).
    """
    # *** START CODE HERE ***
    X_transpose = X.transpose()
    update_theta = np.linalg.solve(X_transpose.dot(X),X_transpose.dot(y))
    return update_theta

In [146]:
my_theta = fit(my_poly, train_y)

In [147]:
my_theta

array([-5.88966782e-03,  6.59271928e-01,  3.19919077e-03, -6.97668231e-02,
       -1.21887628e-04,  1.36463074e-03])

In [112]:
my_poly.dot(my_theta)

array([-1.11583643, -1.00317761,  0.16481194,  0.26698106,  0.02241875,
        1.07023579])

In [113]:
train_y

array([-1.32366975, -0.62183616,  0.74395102,  0.3150024 , -0.83582222,
        1.12780822])

In [114]:
np.sin(np.array([train_x[:,1],]).transpose())

array([[-0.98982144],
       [-0.48619674],
       [ 0.61815899],
       [ 0.03172793],
       [-0.97880245],
       [ 0.99886734]])

In [148]:
def create_sin(k, X):
    """
    Generates a sin with polynomial featuremap to the data x.
    Output should be a numpy array whose shape is (n_examples, k+2)

    Args:
        X: Training example inputs. Shape (n_examples, 2).
    """
    # *** START CODE HERE ***
    polyList = [*range(k+1)]
    col_1 = np.array([X[:,0],]).transpose()
    col_2 = np.array([X[:,1],]).transpose()

    clone_col_2 = np.tile(col_2, (1,k))
    feature_cloned = np.hstack([col_1,clone_col_2])
    feature_poly = np.power(feature_cloned,polyList)

    col_2_sin = np.sin(col_2)
    feature_poly_sin = np.hstack([feature_poly,col_2_sin])
    return feature_poly_sin

In [149]:
my_features_sin = create_sin(3,train_x)

In [150]:
my_theta = fit(my_features_sin, train_y)
my_theta

array([-3.77972878e-04,  4.39856036e-02, -2.71432228e-04, -2.35324990e-03,
        9.35742679e-01])