In [1]:
import argparse
import functools
import numpy as np
import matplotlib.pyplot as plt

In [5]:
np.exp([1000, 0.001])

array([      inf, 1.0010005])

In [6]:
np.max([100,1,40])

100

In [7]:
np.exp([100,1,40] - np.max([100,1,40]) )

array([1.00000000e+00, 1.01122149e-43, 8.75651076e-27])

In [9]:
x = np.array([[10000, 10010, 10]])

In [11]:
np.exp(x - np.max(x)) / np.sum(np.exp(x - np.max(x)))*100

array([[4.53978687e-03, 9.99954602e+01, 0.00000000e+00]])

In [12]:
np.exp(x - np.max(x, axis=1)) / np.sum(np.exp(x - np.max(x, axis=1)), axis=1)

array([[4.53978687e-05, 9.99954602e-01, 0.00000000e+00]])

In [26]:
x = np.array([[1,1], [2,2], [3,3]])

In [15]:
np.exp(x - np.max(x)) / np.sum(np.exp(x - np.max(x, axis=1)), axis=1)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [19]:
np.exp(x - np.max(x)).shape

(2, 3)

In [27]:
np.sum(np.exp(x - np.max(x)), axis=1).shape

(3,)

In [29]:
np.exp(x - np.max(x))/np.sum(np.exp(x - np.max(x)), axis=1)[:,None]

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5]])

In [23]:
np.divide(np.exp(x - np.max(x)), np.sum(np.exp(x - np.max(x)), axis=1))

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [28]:
np.sum(np.exp(x - np.max(x)), axis=1)

array([0.27067057, 0.73575888, 2.        ])

In [31]:
np.random.randn(5,2)

array([[ 0.17658163, -1.32973838],
       [-0.14430154, -0.32918675],
       [ 0.6196932 ,  0.09563642],
       [-1.18821118,  0.60552998],
       [-1.66552394, -0.6664839 ]])

In [53]:
x = np.array([1,10,100])

In [51]:
def sigmoid(x):
    "Numerically-stable sigmoid function."
    output = np.zeros_like(x)
    output[x >=0] = 1 / (1 + np.exp(-x[x >=0]))
    output[x<0] = np.exp(x[x<0])/ (1+ np.exp(x[x<0]))
    return output

In [54]:
sigmoid(x)

array([0, 0, 1])

In [41]:
x>0

array([ True,  True,  True])

In [48]:
1/(1+np.exp(-x))

array([0.73105858, 0.9999546 , 1.        ])

In [59]:
np.linspace(0,100, num=5)

array([  0.,  25.,  50.,  75., 100.])